Repository se2-2021-tue-16-okulewicz/Project-Group-B, pull requests merged in 2021-03, with the labels that each got.

#19 Adding test and prettier actions to github
  .github/workflows/backend-tests.yml
  .github/workflows/mobile-tests.yml
  .github/workflows/prettier.yml
  .github/workflows/webapp-tests.yml
  mobileapp/.gitignore
  mobileapp/App.tsx
  mobileapp/README.MD
  mobileapp/app.json
  mobileapp/babel.config.js
  mobileapp/package-lock.json
  mobileapp/package.json
  webapp/src/App.css
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/app/store.ts
  webapp/src/features/counter/Counter.module.css
  webapp/src/features/counter/Counter.tsx
  webapp/src/features/counter/counterSlice.ts
  webapp/src/index.css
  webapp/src/index.tsx
  webapp/src/serviceWorker.ts
  webapp/src/setupTests.ts
  webapp/tsconfig.json
Labels: feature

#22 Registering a Dog as Lost (Backend)
  Backend/.idea/.name
  Backend/SE-Backend.iml
  Backend/src/main/java/se/backend/SEBackend.java
  Backend/src/main/java/se/backend/controller/internal/DogsController.java
  Backend/src/main/java/se/backend/controller/internal/EmptyController.java
  Backend/src/main/java/se/backend/dao/DogBehaviorRepository.java
  Backend/src/main/java/se/backend/dao/LostDogRepository.java
  Backend/src/main/java/se/backend/dao/PictureRepository.java
  Backend/src/main/java/se/backend/exceptions/ExceptionDetails.java
  Backend/src/main/java/se/backend/exceptions/ExceptionHelper.java
  Backend/src/main/java/se/backend/exceptions/types/AccountExistsException.java
  Backend/src/main/java/se/backend/exceptions/types/GenericBadRequestException.java
  Backend/src/main/java/se/backend/exceptions/types/InvalidCredentialsException.java
  Backend/src/main/java/se/backend/exceptions/types/InvalidDataFormatException.java
  Backend/src/main/java/se/backend/exceptions/types/InvalidDateException.java
  Backend/src/main/java/se/backend/exceptions/types/InvalidFileException.java
  Backend/src/main/java/se/backend/exceptions/types/InvalidOperationException.java
  Backend/src/main/java/se/backend/exceptions/types/NotAFileException.java
  Backend/src/main/java/se/backend/exceptions/types/ResourceNotFoundException.java
  Backend/src/main/java/se/backend/exceptions/types/UnauthorizedException.java
  Backend/src/main/java/se/backend/model/Location.java
  Backend/src/main/java/se/backend/model/Picture.java
  Backend/src/main/java/se/backend/model/dogs/Dog.java
  Backend/src/main/java/se/backend/model/dogs/DogBehavior.java
  Backend/src/main/java/se/backend/model/dogs/LostDog.java
  Backend/src/main/java/se/backend/service/empty/EmptyMainService.java
  Backend/src/main/java/se/backend/service/empty/EmptyService.java
  Backend/src/main/java/se/backend/service/lostdogs/LostDogMainService.java
  Backend/src/main/java/se/backend/service/lostdogs/LostDogService.java
  Backend/src/main/java/se/backend/utils/JsonDateDeserializer.java
  Backend/src/main/java/se/backend/utils/JsonDateSerializer.java
  Backend/src/main/java/se/backend/utils/Response.java
  Backend/src/main/java/se/backend/wrapper/dogs/LostDogWithBehaviors.java
  Backend/src/main/java/se/backend/wrapper/dogs/LostDogWithBehaviorsAndWithPicture.java
  Backend/src/test/java/controller/internal/DogsControllerTest.java
  Backend/src/test/java/service/EmptyServiceTest.java
  Backend/src/test/java/service/LostDogServiceTest.java
  Backend/src/test/resources/application.properties
  Backend/src/test/resources/data.sql
Labels: feature

#24 Fix of registered lost dog (Frontend)
  .github/workflows/backend-tests.yml
  .github/workflows/mobile-tests.yml
  .github/workflows/prettier.yml
  .github/workflows/webapp-tests.yml
  mobileapp/.gitignore
  mobileapp/App.tsx
  mobileapp/README.MD
  mobileapp/app.json
  mobileapp/babel.config.js
  mobileapp/package-lock.json
  mobileapp/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.css
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/app/actions.ts
  webapp/src/app/fetching.ts
  webapp/src/app/reducer.ts
  webapp/src/app/store.ts
  webapp/src/app/utility.ts
  webapp/src/dog/dogClasses.tsx
  webapp/src/features/counter/Counter.module.css
  webapp/src/features/counter/Counter.tsx
  webapp/src/features/counter/counterSlice.ts
  webapp/src/index.css
  webapp/src/index.tsx
  webapp/src/registerDog/ImageUpload.css
  webapp/src/registerDog/ImageUpload.tsx
  webapp/src/registerDog/LostDog.jpg
  webapp/src/registerDog/registerDog.tsx
  webapp/src/serviceWorker.ts
  webapp/src/setupTests.ts
  webapp/tests/dogClasses.test.tsx
  webapp/tests/registerDog.test.tsx
  webapp/tsconfig.json
Labels: fix

#23 Backend/feature/sign in
  Backend/pom.xml
  Backend/src/main/java/se/backend/controller/internal/UserController.java
  Backend/src/main/java/se/backend/dao/AdminAccountRepository.java
  Backend/src/main/java/se/backend/dao/DogShelterAccountRepository.java
  Backend/src/main/java/se/backend/dao/DogShelterRepository.java
  Backend/src/main/java/se/backend/dao/UserAccountRepository.java
  Backend/src/main/java/se/backend/model/account/Account.java
  Backend/src/main/java/se/backend/model/account/Address.java
  Backend/src/main/java/se/backend/model/account/AdminAccount.java
  Backend/src/main/java/se/backend/model/account/DogShelterAccount.java
  Backend/src/main/java/se/backend/model/account/Shelter.java
  Backend/src/main/java/se/backend/model/account/UserAccount.java
  Backend/src/main/java/se/backend/service/login/LoginMainService.java
  Backend/src/main/java/se/backend/service/login/LoginService.java
  Backend/src/main/java/se/backend/wrapper/account/AuthenticationResults.java
  Backend/src/main/java/se/backend/wrapper/account/LoginInfo.java
  Backend/src/main/java/se/backend/wrapper/account/UserType.java
  Backend/src/test/java/controller/internal/UserControllerTest.java
  Backend/src/test/java/service/LoginServiceTest.java
  Backend/src/test/resources/data.sql
Labels: feature

#27 Fixed login request, added dogs request authorization
  Backend/src/main/java/se/backend/controller/internal/DogsController.java
  Backend/src/main/java/se/backend/controller/internal/UserController.java
  Backend/src/main/java/se/backend/exceptions/ExceptionHelper.java
  Backend/src/main/java/se/backend/exceptions/types/UnauthorizedException.java
  Backend/src/main/java/se/backend/service/login/LoginMainService.java
  Backend/src/main/java/se/backend/service/login/LoginService.java
  Backend/src/test/java/controller/internal/DogsControllerTest.java
  Backend/src/test/java/controller/internal/UserControllerTest.java
  Backend/src/test/java/service/LoginServiceTest.java
Labels: feature

#18 Register a Dog (Frontend)
  Backend/.gitignore
  Backend/logs/spring.log
  mobileapp/package-lock.json
  mobileapp/package.json
  webapp/.babelrc
  webapp/babel.config.js
  webapp/messages.html
  webapp/oldtests/Apptest.tsx
  webapp/oldtests/dogClassestest.tsx
  webapp/oldtests/registerDogtest.tsx
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/__mocks__/fileMock.js
  webapp/src/__mocks__/styleMock.js
  webapp/src/app/actions.ts
  webapp/src/app/fetching.ts
  webapp/src/app/reducer.ts
  webapp/src/app/response.ts
  webapp/src/app/store.ts
  webapp/src/config/config.ts
  webapp/src/config/development.json
  webapp/src/config/production.json
  webapp/src/dog/dogClasses.ts
  webapp/src/dog/dogEnums.ts
  webapp/src/dog/dogInterfaces.ts
  webapp/src/features/counter/Counter.module.css
  webapp/src/features/counter/Counter.tsx
  webapp/src/features/counter/counterSlice.ts
  webapp/src/index.tsx
  webapp/src/logo.svg
  webapp/src/registerDog/ImageUpload.css
  webapp/src/registerDog/ImageUpload.test.tsx
  webapp/src/registerDog/ImageUpload.tsx
  webapp/src/registerDog/__snapshots__/registerDog.test.tsx.snap
  webapp/src/registerDog/registerDog.test.tsx
  webapp/src/registerDog/registerDog.tsx
  webapp/src/serviceWorker.ts
  webapp/tsconfig.json
Labels: feature

#29 Implement Sign-in (Frontend)
  Backend/logs/spring.log
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/app/actions.ts
  webapp/src/app/fetching.ts
  webapp/src/app/reducer.ts
  webapp/src/index.css
  webapp/src/registerDog/ImageUpload.tsx
  webapp/src/registerDog/registerDog.tsx
  webapp/src/registerLogin/Login.css
  webapp/src/registerLogin/Login.test.tsx
  webapp/src/registerLogin/Login.tsx
  webapp/src/registerLogin/loginRegisterInterfaces.ts
  webapp/src/utilityComponents/ErrorDialog.tsx
  webapp/src/utilityComponents/Footer.css
  webapp/src/utilityComponents/Footer.tsx
  webapp/src/utilityComponents/LoadingPopup.css
  webapp/src/utilityComponents/LoadingPopup.tsx
Labels: feature

#30 Initial implementation of a List of Dogs (Frontend)
  webapp/src/App.tsx
  webapp/src/dogsList/listWithDogs.test.tsx
  webapp/src/dogsList/listWithDogs.tsx
  webapp/src/registerDog/ImageUpload.tsx
  webapp/src/registerDog/__snapshots__/registerDog.test.tsx.snap
  webapp/src/registerDog/registerDog.test.tsx
  webapp/src/registerDog/registerDog.tsx
  webapp/src/registerLogin/Login.tsx
  webapp/src/utilityComponents/Footer.css
Labels: feature

#40 Add user id in authentication results and save it in frontend
  Backend/.idea/misc.xml
  Backend/logs/spring.log
  Backend/src/main/java/se/backend/service/login/LoginMainService.java
  Backend/src/main/java/se/backend/wrapper/account/AuthenticationResults.java
  Backend/src/test/java/controller/internal/UserControllerTest.java
  webapp/src/app/fetching.ts
  webapp/src/config/config.ts
  webapp/src/config/development.json
  webapp/src/config/production.json
  webapp/src/registerLogin/Login.tsx
  webapp/src/registerLogin/loginRegisterInterfaces.ts
  webapp/src/utilityComponents/Footer.tsx
Labels: feature

#41 Registered dog does not have the owner
  Backend/.idea/modules.xml
  Backend/pom.xml
  Backend/se-backend.iml
  Backend/src/main/java/se/backend/controller/internal/DogsController.java
  Backend/src/main/java/se/backend/service/MainConfig.java
  Backend/src/main/java/se/backend/service/login/LoginMainService.java
  Backend/src/main/java/se/backend/service/login/LoginService.java
  Backend/src/main/java/se/backend/service/lostdogs/LostDogMainService.java
  Backend/src/main/java/se/backend/service/lostdogs/LostDogService.java
  Backend/src/main/resources/application-mysql-dev-example.properties
  Backend/src/main/resources/application-prod-mysql.properties
  Backend/src/test/java/controller/internal/DogsControllerTest.java
  Backend/src/test/java/service/LoginServiceTest.java
  Backend/src/test/java/service/LostDogServiceTest.java
  Backend/src/test/resources/application.properties
Labels: fix

#42 Backend validation, more backend tests (failed), transactions
  Backend/.idea/aws.xml
  Backend/.idea/misc.xml
  Backend/src/main/java/se/backend/controller/internal/DogsController.java
  Backend/src/main/java/se/backend/exceptions/ExceptionHelper.java
  Backend/src/main/java/se/backend/model/Picture.java
  Backend/src/main/java/se/backend/model/dogs/Dog.java
  Backend/src/main/java/se/backend/model/dogs/LostDog.java
  Backend/src/main/java/se/backend/service/lostdogs/LostDogMainService.java
  Backend/src/main/java/se/backend/utils/StringUtils.java
  Backend/src/main/java/se/backend/wrapper/dogs/LostDogWithBehaviors.java
  Backend/src/test/java/controller/internal/DogsControllerTest.java
  Backend/src/test/java/model/PictureTest.java
  Backend/src/test/java/model/dogs/LostDogWithBehaviorsTest.java
Labels: refactor

#44 Add logout to existing login feature
  Backend/src/main/java/se/backend/controller/internal/UserController.java
  Backend/src/main/java/se/backend/service/login/LoginMainService.java
  Backend/src/main/java/se/backend/service/login/LoginService.java
  Backend/src/test/java/controller/internal/UserControllerTest.java
  Backend/src/test/java/service/LoginServiceTest.java
  webapp/src/App.tsx
  webapp/src/app/actions.ts
  webapp/src/app/fetching.ts
  webapp/src/app/reducer.ts
  webapp/src/utilityComponents/Footer.tsx
Labels: feature

#46 Marking lost dogs as found - new endpoint (backend)
  Backend/src/main/java/se/backend/controller/internal/DogsController.java
  Backend/src/main/java/se/backend/dao/LostDogRepository.java
  Backend/src/main/java/se/backend/model/account/Account.java
  Backend/src/main/java/se/backend/model/account/DogShelterAccount.java
  Backend/src/main/java/se/backend/service/login/LoginMainService.java
  Backend/src/main/java/se/backend/service/lostdogs/LostDogMainService.java
  Backend/src/main/java/se/backend/service/lostdogs/LostDogService.java
  Backend/src/test/java/controller/internal/DogsControllerTest.java
  Backend/src/test/java/controller/internal/UserControllerTest.java
  Backend/src/test/java/service/LoginServiceTest.java
  Backend/src/test/java/service/LostDogServiceTest.java
  Backend/src/test/resources/data.sql
Labels: refactor
