Repository se2-2021-tue-16-okulewicz/Project-Group-B, pull requests merged in 2021-04, with the labels that each got.

#50 Register regular account (Backend)
  Backend/.idea/compiler.xml
  Backend/.idea/csv-plugin.xml
  Backend/.idea/modules.xml
  Backend/pom.xml
  Backend/se-backend.iml
  Backend/src/main/java/se/backend/controller/internal/UserController.java
  Backend/src/main/java/se/backend/dao/UserAccountRepository.java
  Backend/src/main/java/se/backend/model/account/UserAccount.java
  Backend/src/main/java/se/backend/model/dogs/Dog.java
  Backend/src/main/java/se/backend/service/login/LoginMainService.java
  Backend/src/main/java/se/backend/service/login/LoginService.java
  Backend/src/main/java/se/backend/utils/StringUtils.java
  Backend/src/test/java/controller/internal/UserControllerTest.java
  Backend/src/test/java/service/LoginServiceTest.java
  Backend/src/test/java/utils/StringUtilsTest.java
  Backend/src/test/resources/data.sql
Labels: feature, low priority

#51 Register regular account (webapp)
  Backend/.idea/compiler.xml
  Backend/.idea/modules.xml
  webapp/src/App.tsx
  webapp/src/app/actions.ts
  webapp/src/app/fetching.ts
  webapp/src/app/reducer.ts
  webapp/src/registerLogin/Login.tsx
  webapp/src/registerLogin/RegisterRegularUser.test.tsx
  webapp/src/registerLogin/RegisterRegularUser.tsx
  webapp/src/registerLogin/loginRegisterInterfaces.ts
Labels: feature, low priority

#34 Implement Sign-in (Mobile)
  .DS_Store
  Backend/.idea/compiler.xml
  Backend/se-backend.iml
  Backend/src/main/resources/application-mysql-dev-example.properties
  Backend/src/main/resources/application-prod-mysql.properties
  mobileapp/.gitignore
  mobileapp/App.tsx
  mobileapp/README.MD
  mobileapp/assets/fonts/SpaceMono-Regular.ttf
  mobileapp/assets/images/adaptive-icon.png
  mobileapp/assets/images/altCar.png
  mobileapp/assets/images/dog-paw.png
  mobileapp/assets/images/favicon.png
  mobileapp/assets/images/icon.png
  mobileapp/assets/images/splash.png
  mobileapp/components/dogs/DogsList.tsx
  mobileapp/components/loginRegisterInterfaces.ts
  mobileapp/components/register-login/LogInRegister.tsx
  mobileapp/components/register-login/SignIn.tsx
  mobileapp/config/config.ts
  mobileapp/config/development-example.json
  mobileapp/config/development.json
  mobileapp/config/production.json
  mobileapp/constants/account.ts
  mobileapp/hooks/useCachedResources.ts
  mobileapp/hooks/useColorScheme.ts
  mobileapp/hooks/useColorScheme.web.ts
  mobileapp/navigation/BottomTabNavigator.tsx
  mobileapp/navigation/LinkingConfiguration.ts
  mobileapp/navigation/index.tsx
  mobileapp/package-lock.json
  mobileapp/package.json
  mobileapp/redux/actions.tsx
  mobileapp/redux/fetching.tsx
  mobileapp/redux/reducer.tsx
  mobileapp/redux/response.ts
  mobileapp/redux/store.ts
  mobileapp/redux/utility.ts
  mobileapp/reset-cache/.expo/README.md
  mobileapp/reset-cache/.expo/settings.json
  mobileapp/tests/SignInTest.ts
  mobileapp/tsconfig.json
  webapp/package-lock.json
Labels: feature

#65 Bugfix of user editing (backend)
  Backend/src/main/java/se/backend/service/user/UserMainService.java
  Backend/src/test/java/controller/internal/UserControllerTest.java
  Backend/src/test/java/service/UserServiceTest.java
Labels: fix

#64 Refactoring things to match the other group (Mobile)
  mobileapp/components/dogs/DogsList.tsx
  mobileapp/components/dogs/dog/dogInterfaces.ts
  mobileapp/redux/actions.tsx
  mobileapp/redux/fetching.tsx
  mobileapp/redux/reducer.tsx
Labels: refactor

#67 Edit the details of a dog I registered as Lost (Frontend)
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/app/actions.ts
  webapp/src/app/fetching.test.ts
  webapp/src/app/fetching.ts
  webapp/src/app/reducer.ts
  webapp/src/commoncomponents/imageGrid.tsx
  webapp/src/dog/dogClasses.ts
  webapp/src/dog/dogEnums.ts
  webapp/src/dog/dogInterfaces.ts
  webapp/src/dogDetails/dogDetails.test.tsx
  webapp/src/dogDetails/dogDetails.tsx
  webapp/src/dogsList/listWithDogs.tsx
  webapp/src/dontdelete_newlistfilters/dogsList/new_listWithDogs.tsx
  webapp/src/dontdelete_newlistfilters/new_settings/new_settings.tsx
  webapp/src/editDogDetails/editDogDetails.tsx
  webapp/src/registerDog/ImageUpload.tsx
  webapp/src/registerDog/registerDog.test.tsx
  webapp/src/registerDog/registerDog.tsx
  webapp/src/registerLogin/Login.tsx
  webapp/src/registerLogin/RegisterRegularUser.tsx
  webapp/src/settings/settings.tsx
  webapp/src/utilityComponents/Footer.css
  webapp/src/utilityComponents/Footer.tsx
  webapp/src/utilityComponents/uitilities.ts
  webapp/src/utilityComponents/utilities.ts
Labels: feature

#71 Edit contact information (Frontend)
  webapp/src/App.tsx
  webapp/src/app/actions.ts
  webapp/src/app/fetching.ts
  webapp/src/app/reducer.ts
  webapp/src/commoncomponents/imageGrid.tsx
  webapp/src/contactInfo/ContactInfo.test.tsx
  webapp/src/contactInfo/ContactInfo.tsx
  webapp/src/contactInfo/EditContactInfo.test.tsx
  webapp/src/contactInfo/EditContactInfo.tsx
  webapp/src/contactInfo/contactInfoInterfaces.ts
  webapp/src/dogsList/listWithDogs.tsx
  webapp/src/editDogDetails/editDogDetails.tsx
  webapp/src/registerDog/ImageUpload.css
  webapp/src/registerDog/registerDog.tsx
  webapp/src/registerLogin/RegisterRegularUser.tsx
  webapp/src/settings/settings.tsx
  webapp/src/utilityComponents/utilities.ts
  webapp/src/utilityComponents/validation.tsx
Labels: feature

#63 Register regular user in mobile
  mobileapp/components/register-login/LogInRegister.tsx
  mobileapp/components/register-login/Register.tsx
  mobileapp/components/register-login/SignIn.tsx
  mobileapp/components/register-login/loginRegisterInterfaces.ts
  mobileapp/constants/account.ts
  mobileapp/redux/actions.tsx
  mobileapp/redux/fetching.tsx
  mobileapp/redux/reducer.tsx
Labels: feature

#72 Fix of behaviors (Frontend)
  webapp/src/App.tsx
  webapp/src/dogDetails/dogDetails.tsx
  webapp/src/editDogDetails/editDogDetails.tsx
  webapp/src/registerDog/ImageUpload.css
  webapp/src/registerDog/ImageUpload.tsx
Labels: fix
